# GIT VS GITHUB #


# GIT IS A DISTRIBUTED VERSION CONTROL SYSTEM # WHILE GITHUB IS A RPOSITORY HOSTING SERVICE #

# GIT INTODUCTION #

# GIT IS A 'DISTRUBUTED VERION CONTROL SYSTEM', WHY BECAUSE IT ENABLES THE COLLABROATION OF MANY TEAMS #

# GITHUB INTODUCTION   #

# A REMOTE HOSTING REPOSITORY IT BASICALLY ALLOWS YOU TO HOST YOUR FILES FROM GIT AND ENABLES THE COLLABORATION OF VARIOUS TEAMS #



